name: gitflow-action
description: Automatically creates and merges pull requests from `master` to `dev` and from `release` to `master`.
author: Bruno Logerfo

branding:
  icon: git-merge
  color: white

inputs:
  github-token:
    description: The `GITHUB_TOKEN` secret.
    required: true
  release:
    description: The `release` branch.
    default: release
  release-regex:
    description: The `release` branch regex.
    default: null
  dev:
    description: The `dev` branch.
    default: dev
  master:
    description: The `master` branch.
    default: master
  label:
    description: The pull request label.
    default: gitflow
  auto-merge:
    description: If `true`, will try to automatically merge pull requests. Can also be set to `pull_request_review`, `check_run`, `push`, or a comma-separated combination of these values to only merge when handling the named events.
    default: true
  require-merge:
    description: If an attempted merge fails, the action is considered to have failed.
    default: false

runs:
  using: 'node12'
  main: 'dist/index.js'
