name: gitflow-action
description: Automatically creates, approves and merges pull requests from master to dev and from release to master.
author: Bruno Logerfo

branding:
  icon: git-merge
  color: white

runs:
  using: 'node12'
  main: 'lib/main.js'
